# 3. pandas数据处理作业

3.1 读取excel数据并进行抽样resample()

只保留data中的open，获取data的数据类型与后5个值：

                      close    high     low    open    volume
datetime                                                     
2017-01-03 15:00:00  115.99  117.06  115.14  115.43  16232125
2017-01-04 15:00:00  116.28  116.42  115.21  115.99  29656234
2017-01-05 15:00:00  116.07  116.64  115.64  116.07  26436646
2017-01-06 15:00:00  115.21  116.07  114.86  116.07  17195598
2017-01-09 15:00:00  115.35  115.99  114.86  115.64  14908745
2017-01-10 15:00:00  115.28  115.64  114.93  115.21   7996636
2017-01-11 15:00:00  115.07  115.64  115.00  115.64   9166532
2017-01-12 15:00:00  114.78  115.35  114.71  115.21   8295650
2017-01-13 15:00:00  115.85  115.99  114.64  114.64  19024943
2017-01-16 15:00:00  117.92  118.20  114.64  115.57  53249124
2017-01-17 15:00:00  116.85  117.77  116.56  117.21  12555292
2017-01-18 15:00:00  117.42  117.85  116.49  116.92  11478663
2017-01-19 15:00:00  117.77  118.49  116.99  116.99  12180687
2017-01-20 15:00:00  118.06  118.63  117.49  118.06  14285968
2017-01-

datetime
2017-11-14 15:00:00    119.62
2017-11-15 15:00:00    117.84
2017-11-16 15:00:00    117.75
2017-11-17 15:00:00    116.25
2017-11-20 15:00:00    118.97
Name: open, dtype: float64

3.2 表示在【0-31】这32个数字中分成8行4列  

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


3.3 将第5个到第7个改为12  
arr=np.arange(10)  最后输出结果为[ 0  1  2  3  4 12 12 12  8  9]

[ 0  1  2  3  4 12 12 12  8  9]


3.4如何方便的计算两个时间的差，如两个时间相差几天，几小时等，写出代码，列出式子